version: '3'

services:

  postgres:
    container_name: postgres_container
    image: postgres:12.3
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/roulette_postgres
    ports:
      - "5432:5432"
    networks:
      postgres:
        aliases:
          - postgres
    restart: unless-stopped

  php-fpm:
    build:
      context: ./php-fpm
    depends_on:
      - postgres
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}
    volumes:
      - ../src:/var/www
    networks:
      - postgres

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    links:
      - php-fpm
    networks:
      - postgres
    depends_on:
      - php-fpm
    ports:
      - "8081:80"

volumes:
  postgres:

networks:
  postgres:


