doctrine:
    dbal:
        default_connection: pgsql
        connections:
            pgsql:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_pgsql'
                server_version: '12.3'
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci

    orm:
        default_entity_manager: pg
        entity_managers:
            pg:
                connection: pgsql
                mappings:
                    Pg:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Pg
